//
//  TipsDummy.swift
//  Muzzez School
//
//  Created by Gus Adi on 24/05/21.
//

import Foundation

struct TipsDummy {
  let tipsDummy = [
    Tips(title: "Take care your instrument", image: "guitarImg", isi: """
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis in massa vel cursus. Nulla aliquam mauris posuere nunc suscipit vehicula. Duis eu porta velit. Vestibulum in mauris quam. Ut ut varius odio. Aenean mollis dictum eros id blandit. Sed fringilla consequat efficitur. Pellentesque facilisis lorem malesuada libero iaculis, ut viverra nulla dignissim. Nam sit amet tellus nec dui lobortis tempus. Duis congue eget felis sed ultrices. Duis ultricies, nisl at tincidunt euismod, neque mi pulvinar est, in auctor lacus odio ac urna. Nam quis faucibus lectus, vitae cursus massa.

      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ullamcorper sit amet urna non consectetur. Sed congue dignissim fermentum. Vivamus sed enim ut massa gravida mattis. Nulla scelerisque diam et risus dapibus facilisis. Praesent viverra commodo eros, quis euismod libero bibendum id. Aenean condimentum feugiat leo et viverra. Aliquam velit nibh, tincidunt vitae ante sed, aliquet commodo sapien. Phasellus scelerisque euismod augue, a mattis nulla. Curabitur maximus velit in dui venenatis, quis tristique nibh auctor. Duis non nisl nec diam volutpat finibus.

      Etiam ac enim sem. Maecenas sollicitudin massa ut justo maximus, eu semper nulla porta. Quisque mauris nibh, varius aliquam efficitur sit amet, egestas quis nulla. Vestibulum non nibh blandit, finibus neque et, consequat neque. Nam libero enim, tempus eu varius quis, fermentum ac est. Aenean vitae tempor lacus. Nullam dignissim mi lacus. Morbi tincidunt convallis neque, in finibus ante ornare non. Fusce vestibulum vehicula mollis.

      Pellentesque eu purus accumsan, blandit ante eget, scelerisque enim. Nunc id efficitur eros. Nulla facilisi. In finibus auctor consectetur. Vestibulum eu neque metus. Phasellus et nunc ac sapien placerat rhoncus non eget tellus. Proin eget sapien nec diam lacinia bibendum. Quisque orci odio, porttitor id nisl at, porta sollicitudin felis. Mauris vel nisi fermentum, lacinia turpis sed, placerat dolor. Maecenas tellus ante, mollis eget tellus a, porta efficitur elit. Donec quis hendrerit risus. In ultricies diam eget lacus finibus congue. Nunc facilisis nisi dui, non dignissim leo congue ac. Suspendisse vestibulum, sapien id tincidunt venenatis, lorem diam ornare neque, a vehicula est mauris ac justo. Fusce eleifend, lorem accumsan efficitur tempus, odio ex gravida ante, sed mattis nunc nisi id nulla. Sed odio leo, posuere et nunc ac, semper interdum sapien.

      Nam vitae dui sit amet neque interdum sodales. Nam efficitur mauris et velit volutpat, quis dapibus mauris blandit. Pellentesque lacinia scelerisque lorem vitae tincidunt. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent eu ipsum orci. Sed ac tellus neque. Donec id blandit mi. Sed sit amet varius sem. Praesent eget eros posuere, pellentesque nibh iaculis, iaculis neque. Aenean sollicitudin sem eget risus finibus, in dapibus ante dapibus. Vivamus porta gravida quam, at gravida augue vulputate eget. Morbi iaculis id leo a ullamcorper. Aenean commodo lorem quis lobortis malesuada.
  """),
      Tips(title: "Take care your instrument", image: "guitarImg", isi: """
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis in massa vel cursus. Nulla aliquam mauris posuere nunc suscipit vehicula. Duis eu porta velit. Vestibulum in mauris quam. Ut ut varius odio. Aenean mollis dictum eros id blandit. Sed fringilla consequat efficitur. Pellentesque facilisis lorem malesuada libero iaculis, ut viverra nulla dignissim. Nam sit amet tellus nec dui lobortis tempus. Duis congue eget felis sed ultrices. Duis ultricies, nisl at tincidunt euismod, neque mi pulvinar est, in auctor lacus odio ac urna. Nam quis faucibus lectus, vitae cursus massa.

      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ullamcorper sit amet urna non consectetur. Sed congue dignissim fermentum. Vivamus sed enim ut massa gravida mattis. Nulla scelerisque diam et risus dapibus facilisis. Praesent viverra commodo eros, quis euismod libero bibendum id. Aenean condimentum feugiat leo et viverra. Aliquam velit nibh, tincidunt vitae ante sed, aliquet commodo sapien. Phasellus scelerisque euismod augue, a mattis nulla. Curabitur maximus velit in dui venenatis, quis tristique nibh auctor. Duis non nisl nec diam volutpat finibus.

      Etiam ac enim sem. Maecenas sollicitudin massa ut justo maximus, eu semper nulla porta. Quisque mauris nibh, varius aliquam efficitur sit amet, egestas quis nulla. Vestibulum non nibh blandit, finibus neque et, consequat neque. Nam libero enim, tempus eu varius quis, fermentum ac est. Aenean vitae tempor lacus. Nullam dignissim mi lacus. Morbi tincidunt convallis neque, in finibus ante ornare non. Fusce vestibulum vehicula mollis.

      Pellentesque eu purus accumsan, blandit ante eget, scelerisque enim. Nunc id efficitur eros. Nulla facilisi. In finibus auctor consectetur. Vestibulum eu neque metus. Phasellus et nunc ac sapien placerat rhoncus non eget tellus. Proin eget sapien nec diam lacinia bibendum. Quisque orci odio, porttitor id nisl at, porta sollicitudin felis. Mauris vel nisi fermentum, lacinia turpis sed, placerat dolor. Maecenas tellus ante, mollis eget tellus a, porta efficitur elit. Donec quis hendrerit risus. In ultricies diam eget lacus finibus congue. Nunc facilisis nisi dui, non dignissim leo congue ac. Suspendisse vestibulum, sapien id tincidunt venenatis, lorem diam ornare neque, a vehicula est mauris ac justo. Fusce eleifend, lorem accumsan efficitur tempus, odio ex gravida ante, sed mattis nunc nisi id nulla. Sed odio leo, posuere et nunc ac, semper interdum sapien.

      Nam vitae dui sit amet neque interdum sodales. Nam efficitur mauris et velit volutpat, quis dapibus mauris blandit. Pellentesque lacinia scelerisque lorem vitae tincidunt. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent eu ipsum orci. Sed ac tellus neque. Donec id blandit mi. Sed sit amet varius sem. Praesent eget eros posuere, pellentesque nibh iaculis, iaculis neque. Aenean sollicitudin sem eget risus finibus, in dapibus ante dapibus. Vivamus porta gravida quam, at gravida augue vulputate eget. Morbi iaculis id leo a ullamcorper. Aenean commodo lorem quis lobortis malesuada.
  """),
      Tips(title: "Take care your instrument", image: "guitarImg", isi: """
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis in massa vel cursus. Nulla aliquam mauris posuere nunc suscipit vehicula. Duis eu porta velit. Vestibulum in mauris quam. Ut ut varius odio. Aenean mollis dictum eros id blandit. Sed fringilla consequat efficitur. Pellentesque facilisis lorem malesuada libero iaculis, ut viverra nulla dignissim. Nam sit amet tellus nec dui lobortis tempus. Duis congue eget felis sed ultrices. Duis ultricies, nisl at tincidunt euismod, neque mi pulvinar est, in auctor lacus odio ac urna. Nam quis faucibus lectus, vitae cursus massa.

      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ullamcorper sit amet urna non consectetur. Sed congue dignissim fermentum. Vivamus sed enim ut massa gravida mattis. Nulla scelerisque diam et risus dapibus facilisis. Praesent viverra commodo eros, quis euismod libero bibendum id. Aenean condimentum feugiat leo et viverra. Aliquam velit nibh, tincidunt vitae ante sed, aliquet commodo sapien. Phasellus scelerisque euismod augue, a mattis nulla. Curabitur maximus velit in dui venenatis, quis tristique nibh auctor. Duis non nisl nec diam volutpat finibus.

      Etiam ac enim sem. Maecenas sollicitudin massa ut justo maximus, eu semper nulla porta. Quisque mauris nibh, varius aliquam efficitur sit amet, egestas quis nulla. Vestibulum non nibh blandit, finibus neque et, consequat neque. Nam libero enim, tempus eu varius quis, fermentum ac est. Aenean vitae tempor lacus. Nullam dignissim mi lacus. Morbi tincidunt convallis neque, in finibus ante ornare non. Fusce vestibulum vehicula mollis.

      Pellentesque eu purus accumsan, blandit ante eget, scelerisque enim. Nunc id efficitur eros. Nulla facilisi. In finibus auctor consectetur. Vestibulum eu neque metus. Phasellus et nunc ac sapien placerat rhoncus non eget tellus. Proin eget sapien nec diam lacinia bibendum. Quisque orci odio, porttitor id nisl at, porta sollicitudin felis. Mauris vel nisi fermentum, lacinia turpis sed, placerat dolor. Maecenas tellus ante, mollis eget tellus a, porta efficitur elit. Donec quis hendrerit risus. In ultricies diam eget lacus finibus congue. Nunc facilisis nisi dui, non dignissim leo congue ac. Suspendisse vestibulum, sapien id tincidunt venenatis, lorem diam ornare neque, a vehicula est mauris ac justo. Fusce eleifend, lorem accumsan efficitur tempus, odio ex gravida ante, sed mattis nunc nisi id nulla. Sed odio leo, posuere et nunc ac, semper interdum sapien.

      Nam vitae dui sit amet neque interdum sodales. Nam efficitur mauris et velit volutpat, quis dapibus mauris blandit. Pellentesque lacinia scelerisque lorem vitae tincidunt. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent eu ipsum orci. Sed ac tellus neque. Donec id blandit mi. Sed sit amet varius sem. Praesent eget eros posuere, pellentesque nibh iaculis, iaculis neque. Aenean sollicitudin sem eget risus finibus, in dapibus ante dapibus. Vivamus porta gravida quam, at gravida augue vulputate eget. Morbi iaculis id leo a ullamcorper. Aenean commodo lorem quis lobortis malesuada.
  """),
      Tips(title: "Take care your instrument", image: "guitarImg", isi: """
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis in massa vel cursus. Nulla aliquam mauris posuere nunc suscipit vehicula. Duis eu porta velit. Vestibulum in mauris quam. Ut ut varius odio. Aenean mollis dictum eros id blandit. Sed fringilla consequat efficitur. Pellentesque facilisis lorem malesuada libero iaculis, ut viverra nulla dignissim. Nam sit amet tellus nec dui lobortis tempus. Duis congue eget felis sed ultrices. Duis ultricies, nisl at tincidunt euismod, neque mi pulvinar est, in auctor lacus odio ac urna. Nam quis faucibus lectus, vitae cursus massa.

      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ullamcorper sit amet urna non consectetur. Sed congue dignissim fermentum. Vivamus sed enim ut massa gravida mattis. Nulla scelerisque diam et risus dapibus facilisis. Praesent viverra commodo eros, quis euismod libero bibendum id. Aenean condimentum feugiat leo et viverra. Aliquam velit nibh, tincidunt vitae ante sed, aliquet commodo sapien. Phasellus scelerisque euismod augue, a mattis nulla. Curabitur maximus velit in dui venenatis, quis tristique nibh auctor. Duis non nisl nec diam volutpat finibus.

      Etiam ac enim sem. Maecenas sollicitudin massa ut justo maximus, eu semper nulla porta. Quisque mauris nibh, varius aliquam efficitur sit amet, egestas quis nulla. Vestibulum non nibh blandit, finibus neque et, consequat neque. Nam libero enim, tempus eu varius quis, fermentum ac est. Aenean vitae tempor lacus. Nullam dignissim mi lacus. Morbi tincidunt convallis neque, in finibus ante ornare non. Fusce vestibulum vehicula mollis.

      Pellentesque eu purus accumsan, blandit ante eget, scelerisque enim. Nunc id efficitur eros. Nulla facilisi. In finibus auctor consectetur. Vestibulum eu neque metus. Phasellus et nunc ac sapien placerat rhoncus non eget tellus. Proin eget sapien nec diam lacinia bibendum. Quisque orci odio, porttitor id nisl at, porta sollicitudin felis. Mauris vel nisi fermentum, lacinia turpis sed, placerat dolor. Maecenas tellus ante, mollis eget tellus a, porta efficitur elit. Donec quis hendrerit risus. In ultricies diam eget lacus finibus congue. Nunc facilisis nisi dui, non dignissim leo congue ac. Suspendisse vestibulum, sapien id tincidunt venenatis, lorem diam ornare neque, a vehicula est mauris ac justo. Fusce eleifend, lorem accumsan efficitur tempus, odio ex gravida ante, sed mattis nunc nisi id nulla. Sed odio leo, posuere et nunc ac, semper interdum sapien.

      Nam vitae dui sit amet neque interdum sodales. Nam efficitur mauris et velit volutpat, quis dapibus mauris blandit. Pellentesque lacinia scelerisque lorem vitae tincidunt. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent eu ipsum orci. Sed ac tellus neque. Donec id blandit mi. Sed sit amet varius sem. Praesent eget eros posuere, pellentesque nibh iaculis, iaculis neque. Aenean sollicitudin sem eget risus finibus, in dapibus ante dapibus. Vivamus porta gravida quam, at gravida augue vulputate eget. Morbi iaculis id leo a ullamcorper. Aenean commodo lorem quis lobortis malesuada.
  """),
      Tips(title: "Take care your instrument", image: "guitarImg", isi: """
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum convallis in massa vel cursus. Nulla aliquam mauris posuere nunc suscipit vehicula. Duis eu porta velit. Vestibulum in mauris quam. Ut ut varius odio. Aenean mollis dictum eros id blandit. Sed fringilla consequat efficitur. Pellentesque facilisis lorem malesuada libero iaculis, ut viverra nulla dignissim. Nam sit amet tellus nec dui lobortis tempus. Duis congue eget felis sed ultrices. Duis ultricies, nisl at tincidunt euismod, neque mi pulvinar est, in auctor lacus odio ac urna. Nam quis faucibus lectus, vitae cursus massa.

      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ullamcorper sit amet urna non consectetur. Sed congue dignissim fermentum. Vivamus sed enim ut massa gravida mattis. Nulla scelerisque diam et risus dapibus facilisis. Praesent viverra commodo eros, quis euismod libero bibendum id. Aenean condimentum feugiat leo et viverra. Aliquam velit nibh, tincidunt vitae ante sed, aliquet commodo sapien. Phasellus scelerisque euismod augue, a mattis nulla. Curabitur maximus velit in dui venenatis, quis tristique nibh auctor. Duis non nisl nec diam volutpat finibus.

      Etiam ac enim sem. Maecenas sollicitudin massa ut justo maximus, eu semper nulla porta. Quisque mauris nibh, varius aliquam efficitur sit amet, egestas quis nulla. Vestibulum non nibh blandit, finibus neque et, consequat neque. Nam libero enim, tempus eu varius quis, fermentum ac est. Aenean vitae tempor lacus. Nullam dignissim mi lacus. Morbi tincidunt convallis neque, in finibus ante ornare non. Fusce vestibulum vehicula mollis.

      Pellentesque eu purus accumsan, blandit ante eget, scelerisque enim. Nunc id efficitur eros. Nulla facilisi. In finibus auctor consectetur. Vestibulum eu neque metus. Phasellus et nunc ac sapien placerat rhoncus non eget tellus. Proin eget sapien nec diam lacinia bibendum. Quisque orci odio, porttitor id nisl at, porta sollicitudin felis. Mauris vel nisi fermentum, lacinia turpis sed, placerat dolor. Maecenas tellus ante, mollis eget tellus a, porta efficitur elit. Donec quis hendrerit risus. In ultricies diam eget lacus finibus congue. Nunc facilisis nisi dui, non dignissim leo congue ac. Suspendisse vestibulum, sapien id tincidunt venenatis, lorem diam ornare neque, a vehicula est mauris ac justo. Fusce eleifend, lorem accumsan efficitur tempus, odio ex gravida ante, sed mattis nunc nisi id nulla. Sed odio leo, posuere et nunc ac, semper interdum sapien.

      Nam vitae dui sit amet neque interdum sodales. Nam efficitur mauris et velit volutpat, quis dapibus mauris blandit. Pellentesque lacinia scelerisque lorem vitae tincidunt. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent eu ipsum orci. Sed ac tellus neque. Donec id blandit mi. Sed sit amet varius sem. Praesent eget eros posuere, pellentesque nibh iaculis, iaculis neque. Aenean sollicitudin sem eget risus finibus, in dapibus ante dapibus. Vivamus porta gravida quam, at gravida augue vulputate eget. Morbi iaculis id leo a ullamcorper. Aenean commodo lorem quis lobortis malesuada.
  """)
  ]
}
